-- Saccade PostgreSQL init.
--
-- Application tables are managed by individual services:
--   ChromaDB  → src/saccade/storage/chroma_store.py
--   Redis     → src/saccade/storage/redis_cache.py
--   MLflow    → postgresql://saccade:saccade@localhost:5432/mlflow (auto-created by mlflow server)
