"""Build the v0 master-map inventory with quarantined clusters grayed out.

This first slice intentionally produces only inventory and active/search views.
It does not attempt version-lag analysis, seal enforcement, freeze guarding, or
any process-document move.
"""
# status: diagnostic

from __future__ import annotations

import argparse
from dataclasses import dataclass
from pathlib import Path

try:  # Supports both ``python -m`` and direct script execution.
    from .migration_manifest import (
        MigrationManifest,
        MigrationManifestError,
        parse_migration_manifest,
    )
except ImportError:  # pragma: no cover - exercised by direct CLI use
    from migration_manifest import (
        MigrationManifest,
        MigrationManifestError,
        parse_migration_manifest,
    )


DOCUMENT_SUFFIXES = frozenset({".md", ".yaml", ".yml"})
DEFAULT_OUTPUT = Path("docs/ownership/master_map.generated.md")


@dataclass(frozen=True)
class MasterMap:
    """Generated inventory and the default views that consume it."""

    document_inventory: tuple[str, ...]
    active_index: tuple[str, ...]
    active_search_view: tuple[str, ...]
    gray_out_inventory: tuple[tuple[str, tuple[str, ...]], ...]

    @property
    def grayed_out_files(self) -> frozenset[str]:
        return frozenset(path for _, paths in self.gray_out_inventory for path in paths)


def collect_document_inventory(repo_root: str | Path) -> tuple[str, ...]:
    """Return stable repo-relative Markdown/YAML document paths."""

    root = Path(repo_root).resolve()
    docs_root = root / "docs"
    if not docs_root.is_dir():
        return ()
    output_name = (root / DEFAULT_OUTPUT).resolve()
    return tuple(
        sorted(
            path.relative_to(root).as_posix()
            for path in docs_root.rglob("*")
            if path.is_file()
            and path.suffix in DOCUMENT_SUFFIXES
            and path.resolve() != output_name
        )
    )


def build_master_map(
    manifest: MigrationManifest, *, repo_root: str | Path
) -> MasterMap:
    """Create active/default search views without special rules for any map."""

    inventory = collect_document_inventory(repo_root)
    gray_out_inventory = tuple(
        (name, tuple(sorted(cluster.resolved_files)))
        for name, cluster in manifest.clusters.items()
        if cluster.migration_state == "quarantined"
    )
    grayed_out = frozenset(path for _, paths in gray_out_inventory for path in paths)
    active_index = tuple(path for path in inventory if path not in grayed_out)
    return MasterMap(
        document_inventory=inventory,
        active_index=active_index,
        active_search_view=active_index,
        gray_out_inventory=gray_out_inventory,
    )


def render_master_map(master_map: MasterMap, *, manifest_path: str) -> str:
    """Render the generated skeleton; the complete file list is the inventory."""

    lines = [
        "<!-- Generated by scripts/docs/build_master_map.py; do not edit manually. -->",
        "# Master map inventory (v0)",
        "",
        f"Manifest: `{manifest_path}`",
        "",
        "## Active index and default search view",
        "",
    ]
    if master_map.active_index:
        lines.extend(f"- `{path}`" for path in master_map.active_index)
    else:
        lines.append("- _No active documents._")

    lines.extend(["", "## Quarantined inventory (grayed out by default)", ""])
    if not master_map.gray_out_inventory:
        lines.append("- _No quarantined clusters._")
    for cluster_name, paths in master_map.gray_out_inventory:
        lines.extend(
            [
                f"### {cluster_name}",
                "",
                "Excluded from the active index and default search view.",
                "",
            ]
        )
        lines.extend(f"- `{path}`" for path in paths)
        lines.append("")

    lines.extend(
        [
            "## Inventory summary",
            "",
            f"- documents: {len(master_map.document_inventory)}",
            f"- active: {len(master_map.active_index)}",
            f"- grayed out: {len(master_map.grayed_out_files)}",
            "",
        ]
    )
    return "\n".join(lines)


def write_master_map(
    path: str | Path, master_map: MasterMap, *, manifest_path: str
) -> None:
    output = Path(path)
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(
        render_master_map(master_map, manifest_path=manifest_path), encoding="utf-8"
    )


def master_map_is_current(
    path: str | Path, master_map: MasterMap, *, manifest_path: str
) -> bool:
    """Whether the checked-in artifact exactly matches the deterministic render."""

    output = Path(path)
    try:
        current = output.read_text(encoding="utf-8")
    except OSError:
        return False
    return current == render_master_map(master_map, manifest_path=manifest_path)


def main() -> int:
    parser = argparse.ArgumentParser(description="Build the master-map v0 inventory")
    parser.add_argument(
        "--manifest",
        type=Path,
        default=Path.cwd() / "docs/ownership/doc_migration_manifest.yaml",
    )
    parser.add_argument("--repo-root", type=Path, default=Path.cwd())
    parser.add_argument("--output", type=Path, default=Path.cwd() / DEFAULT_OUTPUT)
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail when the generated artifact is missing or stale; do not rewrite it",
    )
    arguments = parser.parse_args()

    try:
        manifest = parse_migration_manifest(
            arguments.manifest, repo_root=arguments.repo_root
        )
    except MigrationManifestError as error:
        print(f"master map build failed [{error.error_class}]: {error}")
        return 1
    master_map = build_master_map(manifest, repo_root=arguments.repo_root)
    try:
        manifest_display_path = (
            arguments.manifest.resolve()
            .relative_to(arguments.repo_root.resolve())
            .as_posix()
        )
    except ValueError:
        manifest_display_path = arguments.manifest.as_posix()
    if arguments.check:
        if master_map_is_current(
            arguments.output,
            master_map,
            manifest_path=manifest_display_path,
        ):
            print(f"master map is current: {arguments.output}")
            return 0
        print(
            f"master map is stale: regenerate with "
            f"python -m scripts.docs.build_master_map --output {arguments.output}"
        )
        return 1
    write_master_map(
        arguments.output,
        master_map,
        manifest_path=manifest_display_path,
    )
    print(
        f"master map written: {arguments.output} "
        f"({len(master_map.active_index)} active, {len(master_map.grayed_out_files)} grayed out)"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
