#!/usr/bin/env python3
"""Render the native typed field list for ``host_params.cfg`` of the resolved config.

Issue #465 Phase B PR-4a (U2b-a). ``host_params.cfg`` records every ``cfg``/
``kwargs`` key the Python oracle host reads (416 keys). The native strict loader
(``shipping/``) parses it into a typed struct whose fields come from an X-macro
list, ``shipping/include/saccade_shipping/host_cfg_fields.inc``. This tool
derives that list -- key, C++ member name and value type, never a value -- from
the committed ``configs/shipping/mamba_whole_graph.resolved.json``.

The list is the compiled schema: once committed, a re-export that adds, drops,
renames or retypes a ``cfg`` key makes the native loader reject the JSON until
this tool is re-run and the diff reviewed. ``--check`` fails when the committed
list is stale.

Types follow the exporter's JSON literals: ``true``/``false`` -> bool, a number
without ``.``/``e`` -> int, any other number -> float, a string, ``null`` (the
key can only be null in shipping), or a list of ints / strings. An empty list
carries no element type, so its element type must be declared in
``EMPTY_LIST_ELEMENT`` (from ``EvalConfig``'s annotation).

Usage:
  .venv/bin/python scripts/model/render_shipping_host_cfg_schema.py
  .venv/bin/python scripts/model/render_shipping_host_cfg_schema.py --check
"""

# status: stable

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path
from typing import Any

REPO = Path(__file__).resolve().parents[2]
CONFIG = REPO / "configs" / "shipping" / "mamba_whole_graph.resolved.json"
OUTPUT = REPO / "shipping" / "include" / "saccade_shipping" / "host_cfg_fields.inc"

# Element type of lists that are empty in the committed file (``EvalConfig``
# annotation in src/saccade/perception/eval/config.py).
EMPTY_LIST_ELEMENT = {"preprocess_modes": "str"}

_IDENT = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")


class SchemaError(Exception):
    pass


def _number_kind(raw: str) -> str:
    return "float" if any(c in raw for c in ".eE") else "int"


def _load_cfg(path: Path) -> list[tuple[str, Any, str | None]]:
    """Return (key, value, raw number literal) in file order."""

    def keep_literal(kind: str):
        def parse(text: str) -> Any:
            return (kind, text)

        return parse

    doc = json.loads(
        path.read_text(encoding="utf-8"),
        parse_int=keep_literal("int"),
        parse_float=keep_literal("float"),
    )
    cfg = doc["host_params"]["cfg"]
    out: list[tuple[str, Any, str | None]] = []
    for key, value in cfg.items():
        if isinstance(value, tuple):
            out.append((key, value, value[1]))
        else:
            out.append((key, value, None))
    return out


def _cpp_type(key: str, value: Any, raw: str | None) -> str:
    if isinstance(value, bool):
        return "bool"
    if isinstance(value, tuple):
        assert raw is not None
        return "std::int64_t" if _number_kind(raw) == "int" else "double"
    if isinstance(value, str):
        return "std::string"
    if value is None:
        return "NullValue"
    if isinstance(value, list):
        if not value:
            element = EMPTY_LIST_ELEMENT.get(key)
            if element is None:
                raise SchemaError(
                    f"cfg.{key}: empty list has no element type; declare it in EMPTY_LIST_ELEMENT"
                )
        elif all(isinstance(v, tuple) and _number_kind(v[1]) == "int" for v in value):
            element = "int"
        elif all(isinstance(v, str) for v in value):
            element = "str"
        else:
            raise SchemaError(f"cfg.{key}: list is not all ints or all strings")
        return {"int": "IntList", "str": "StringList"}[element]
    raise SchemaError(f"cfg.{key}: unsupported value {value!r}")


def _member(key: str) -> str:
    member = key.replace(".", "_")
    if not _IDENT.match(member):
        raise SchemaError(f"cfg.{key}: no C++ member name")
    return member


def render(path: Path = CONFIG) -> str:
    rows = _load_cfg(path)
    members: dict[str, str] = {}
    lines = [
        "// Generated by scripts/model/render_shipping_host_cfg_schema.py from",
        "// configs/shipping/mamba_whole_graph.resolved.json -- do not edit by hand.",
        '// SACCADE_HOST_CFG_FIELD(member, "json key", type): types only, no values.',
    ]
    for key, value, raw in rows:
        member = _member(key)
        if member in members:
            raise SchemaError(
                f"cfg.{key} and cfg.{members[member]} map to member {member}"
            )
        members[member] = key
        lines.append(
            f'SACCADE_HOST_CFG_FIELD({member}, "{key}", {_cpp_type(key, value, raw)})'
        )
    return "\n".join(lines) + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "--check", action="store_true", help="fail if the committed list is stale"
    )
    args = parser.parse_args(argv)
    try:
        text = render()
    except SchemaError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 2
    if args.check:
        current = OUTPUT.read_text(encoding="utf-8") if OUTPUT.exists() else None
        if current != text:
            print(
                f"{OUTPUT.relative_to(REPO)} is stale; re-run "
                "scripts/model/render_shipping_host_cfg_schema.py and review the diff",
                file=sys.stderr,
            )
            return 1
        return 0
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(text, encoding="utf-8")
    return 0


if __name__ == "__main__":
    sys.exit(main())
