#!/usr/bin/env python3
"""Generate the scripts/ discovery index from each script's own header.

Single source of truth lives IN each script:
  * function  -> module docstring first line (.py) / first description comment (.sh)
  * status    -> `# status: <label>` header line (one of the triage labels)
  * usage     -> presence of argparse / a ``Usage:`` block / getopts / positional args

This tool is the scripts-side mirror of ``scripts/docs/build_master_map.py``. It
(1) upserts a generated table block into each script directory's ``README.md`` and
(2) rewrites the global roll-up ``docs/ownership/scripts_inventory.generated.md``.
With ``--check`` it regenerates in memory and fails if anything on disk is stale,
so ``scripts/pre_push.sh`` can gate drift.

Usage:
    .venv/bin/python scripts/tools/build_scripts_index.py            # write
    .venv/bin/python scripts/tools/build_scripts_index.py --check    # verify, no write
"""

# status: stable

from __future__ import annotations

import ast
import re
import subprocess
import sys
from collections import Counter, defaultdict
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
ROLLUP = REPO / "docs/ownership/scripts_inventory.generated.md"
LABELS = ["stable", "diagnostic", "experiment", "archive-candidate", "generated"]
LABEL_DESC = {
    "stable": "supported workflow entrypoint; keep path stable",
    "diagnostic": "reusable analysis/debug tool, not a main workflow",
    "experiment": "tied to a named experiment or historical sweep",
    "archive-candidate": "no longer active; keep only if referenced by docs/results",
    "generated": "output or cache; should be ignored, not tracked",
}
STATUS_RE = re.compile(r"^#\s*status:\s*(\S+)\s*$")
BEGIN = "<!-- BEGIN generated script index -->"
END = "<!-- END generated script index -->"
BANNER = "<!-- Generated by scripts/tools/build_scripts_index.py; do not edit this block by hand. -->"
# Match the block only when both markers sit at the start of their own line, so a
# literal mention of the marker inside prose (e.g. `<!-- BEGIN ... -->`) is not matched.
BLOCK_RE = re.compile(
    r"(?ms)^" + re.escape(BEGIN) + r".*?^" + re.escape(END) + r"[ \t]*$"
)


def tracked_scripts() -> list[str]:
    out = subprocess.check_output(
        [
            "git",
            "-C",
            str(REPO),
            "ls-files",
            "scripts/*.py",
            "scripts/**/*.py",
            "scripts/*.sh",
            "scripts/**/*.sh",
        ],
        text=True,
    )
    return sorted(out.split())


def tracked_readmes() -> list[str]:
    out = subprocess.check_output(
        [
            "git",
            "-C",
            str(REPO),
            "ls-files",
            "scripts/README.md",
            "scripts/**/README.md",
        ],
        text=True,
    )
    return sorted(out.split())


# A generated block plus an optional preceding "## Script index" heading, used to
# strip orphan blocks from directories that no longer contain any script.
STRIP_RE = re.compile(
    r"(?ms)(?:^##\s*Script index\s*\n+)?"
    + re.escape(BEGIN)
    + r".*?^"
    + re.escape(END)
    + r"[ \t]*\n?"
)


def extract(path: str) -> tuple[str, str, str]:
    """Return (status, description, usage) for a script path."""
    text = (REPO / path).read_text(encoding="utf-8", errors="replace")
    lines = text.splitlines()
    status = ""
    for ln in lines[:60]:
        m = STATUS_RE.match(ln)
        if m:
            status = m.group(1)
            break
    if path.endswith(".py"):
        try:
            doc = ast.get_docstring(ast.parse(text)) or ""
        except SyntaxError:
            doc = ""
        desc = next((ln.strip() for ln in doc.splitlines() if ln.strip()), "")
        head = "\n".join(lines[:60]) + "\n" + doc
        usage = (
            "cli"
            if re.search(
                r"argparse|ArgumentParser|click\.command|^Usage:|\bUsage:", head, re.M
            )
            else "-"
        )
    else:
        desc = ""
        for i, ln in enumerate(lines[:12]):
            s = ln.strip()
            if i == 0 and s.startswith("#!"):
                continue
            if STATUS_RE.match(ln):
                continue
            if s.startswith("#") and any(c.isalpha() for c in s.lstrip("#").strip()):
                desc = s.lstrip("#").strip()
                break
        head = "\n".join(lines[:40])
        usage = "cli" if re.search(r"#\s*Usage|getopts|\$\{?[1-9]", head) else "-"
    return status, desc, usage


def _cell(s: str, width: int = 110) -> str:
    s = " ".join(s.split()).replace("|", r"\|")
    return (s[: width - 1] + "…") if len(s) > width else s


def render_dir_block(dir_rel: str, rows: list[tuple[str, str, str, str]]) -> str:
    """rows: list of (name, status, usage, description)."""
    lines = [
        BEGIN,
        BANNER,
        "",
        "| Script | Status | Usage | Function |",
        "|--------|--------|-------|----------|",
    ]
    for name, status, usage, desc in sorted(rows):
        lines.append(f"| `{name}` | {status} | {usage} | {_cell(desc)} |")
    lines += ["", END]
    return "\n".join(lines)


def upsert_readme(dir_rel: str, block: str) -> tuple[Path, str]:
    readme = REPO / dir_rel / "README.md"
    title = dir_rel.rstrip("/")
    if readme.exists():
        content = readme.read_text(encoding="utf-8")
        m = BLOCK_RE.search(content)
        if m:
            new = content[: m.start()] + block + content[m.end() :]
        else:
            new = content.rstrip("\n") + "\n\n## Script index\n\n" + block + "\n"
    else:
        new = f"# `{title}/`\n\n{block}\n"
    return readme, new


def render_rollup(metas: dict[str, tuple[str, str, str]]) -> str:
    by_dir: dict[str, list[str]] = defaultdict(list)
    for path in metas:
        by_dir[str(Path(path).parent)].append(path)
    counts = Counter(m[0] for m in metas.values())
    out = [
        BANNER.replace("this block", "this file"),
        "# scripts/ inventory (generated)",
        "",
        f"Total tracked scripts: **{len(metas)}**. "
        "Source of truth = each script's own docstring + `# status:` header; "
        "regenerate with `scripts/tools/build_scripts_index.py`.",
        "",
        "> **Classification provenance.** Labels were seeded from a one-time survey, "
        "then the `stable` set was given a semantic role review (2026-07-21) that "
        "moved wired-in analysis/debug tools to `diagnostic` and named study runners "
        "to `experiment`, so `stable` means a supported workflow entrypoint or "
        "path-stability infra — not merely wired-into-code. The source of truth is "
        "each script's `# status:` header; edit that line to correct a label.",
        "",
        "## Status label counts",
        "",
        "| Label | Meaning | Count |",
        "|-------|---------|------:|",
    ]
    for lbl in LABELS:
        out.append(f"| `{lbl}` | {LABEL_DESC[lbl]} | {counts.get(lbl, 0)} |")
    out += ["", "## By directory", ""]
    for d in sorted(by_dir):
        out.append(f"### `{d}/`")
        out.append("")
        out.append("| Script | Status | Usage | Function |")
        out.append("|--------|--------|-------|----------|")
        for path in sorted(by_dir[d]):
            status, desc, usage = metas[path]
            out.append(f"| `{Path(path).name}` | {status} | {usage} | {_cell(desc)} |")
        out.append("")
    return "\n".join(out).rstrip("\n") + "\n"


def build() -> tuple[dict[Path, str], dict[str, tuple[str, str, str]]]:
    scripts = tracked_scripts()
    metas: dict[str, tuple[str, str, str]] = {}
    rows_by_dir: dict[str, list[tuple[str, str, str, str]]] = defaultdict(list)
    for path in scripts:
        status, desc, usage = extract(path)
        metas[path] = (status, desc, usage)
        d = str(Path(path).parent)
        rows_by_dir[d].append((Path(path).name, status, usage, desc))
    writes: dict[Path, str] = {}
    for d, rows in rows_by_dir.items():
        block = render_dir_block(d, rows)
        readme, new = upsert_readme(d, block)
        writes[readme] = new
    # Orphan cleanup: a README whose directory no longer contains any script must
    # not keep a stale generated block (e.g. after an archive cleanup empties a dir).
    script_dirs = set(rows_by_dir)
    for rel in tracked_readmes():
        readme = REPO / rel
        if readme in writes or str(Path(rel).parent) in script_dirs:
            continue
        content = readme.read_text(encoding="utf-8")
        if STRIP_RE.search(content):
            writes[readme] = STRIP_RE.sub("", content).rstrip("\n") + "\n"
    writes[ROLLUP] = render_rollup(metas)
    return writes, metas


def main() -> int:
    check = "--check" in sys.argv
    writes, metas = build()
    stale = []
    for path, content in writes.items():
        cur = path.read_text(encoding="utf-8") if path.exists() else None
        if cur != content:
            stale.append(path)
            if not check:
                path.parent.mkdir(parents=True, exist_ok=True)
                path.write_text(content, encoding="utf-8")
    if check:
        if stale:
            print("scripts index STALE (run build_scripts_index.py):")
            for p in sorted(stale):
                print(f"  {p.relative_to(REPO)}")
            return 1
        print(f"scripts index: ok ({len(metas)} scripts, {len(writes)} files current)")
        return 0
    print(f"scripts index: wrote {len(stale)} file(s) ({len(metas)} scripts indexed)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
