#!/usr/bin/env python3
"""Generate the tests/ discovery index from each test file's own header tags.

Single source of truth lives IN each ``test_*.py``: a one-line module docstring
plus three header comment tags on their own lines, answering three questions —
where the test is responsible, what it guarantees, whether it is still in force:

  * ``# scope: <module>[, <module>]``  responsibility boundary (負責模組範圍);
        an actual module in ``SCOPES``, or ``cross-module`` / ``system``.
        Only scope may take multiple comma-separated values, and only when a
        test genuinely owns several independent modules.
  * ``# function: <label>``   what guarantee it provides (負責功能); one of
        ``FUNCTIONS`` (behavior/contract/regression/acceptance/diagnostic).
  * ``# lifecycle: <label>``  current governance state (生命週期); one of
        ``LIFECYCLES`` (active/legacy/quarantined/deprecated/remove/unclassified).

This tool is the tests-side mirror of ``scripts/tools/build_scripts_index.py``. It
(1) upserts a generated table block into each test directory's ``README.md`` and
(2) rewrites the global roll-up ``docs/ownership/tests_inventory.generated.md``
(scope x function + scope x lifecycle matrices, plus a disposition queue for
tests that are not in a steady state). With ``--check`` it regenerates in memory
and fails if anything on disk is stale, so ``scripts/pre_push.sh`` can gate drift.

Usage:
    .venv/bin/python scripts/tools/build_tests_index.py            # write
    .venv/bin/python scripts/tools/build_tests_index.py --check    # verify, no write
"""

# status: stable

from __future__ import annotations

import ast
import io
import re
import subprocess
import sys
import tokenize
from collections import Counter, defaultdict
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
ROLLUP = REPO / "docs/ownership/tests_inventory.generated.md"

# scope: responsibility boundary. Real modules mirror src/saccade/ (perception/
# holds eval/reid/temporal_yolo=detection/tracking) at package granularity — we do
# NOT split a package into internal features (relink/birth/gmc/...), or scope would
# drift into an unstable feature vocabulary. Governance concepts (h0, seal, packet,
# acceptance targets) are NOT scopes: they are expressed via `function` and the
# module they exercise. `cross-module` / `system` are the two spanning levels.
SCOPE_MODULES = [
    "api",
    "media",
    "pipeline",
    "resource",
    "cognition",
    "storage",
    "perception",
    "detection",
    "reid",
    "eval",
    "tracking",
]
SCOPE_SPANNING = ["cross-module", "system"]
SCOPES = SCOPE_MODULES + SCOPE_SPANNING

# function: what guarantee the test provides (pick one).
FUNCTIONS = ["behavior", "contract", "regression", "acceptance", "diagnostic"]
FUNCTION_DESC = {
    "behavior": "normal functionality matches expectation",
    "contract": "interface / invariant / fail-closed / boundary condition",
    "regression": "pins a fixed bug so it cannot recur",
    "acceptance": "evidence for an issue / phase / delivery sign-off",
    "diagnostic": "observation / localization only; no formal guarantee",
}

# lifecycle: current governance state (pick one).
LIFECYCLES = ["active", "legacy", "quarantined", "deprecated", "remove", "unclassified"]
LIFECYCLE_DESC = {
    "active": "current, maintained, formally in force",
    "legacy": "kept, but contract/structure not yet tidied",
    "quarantined": "temporarily isolated; excluded from formal guarantees",
    "deprecated": "superseded; do not add new dependencies",
    "remove": "confirmed removable; awaiting disposal",
    "unclassified": "migration only; forbidden for newly added tests",
}
# Lifecycles surfaced in the migration/disposition queue — includes `unclassified`
# (the state that most needs to stay visible during migration).
DISPOSITION_LIFECYCLES = [
    "legacy",
    "quarantined",
    "deprecated",
    "remove",
    "unclassified",
]
# Lifecycles that must carry a `# lifecycle-note:` reason/Issue (rule 5).
# `unclassified` is deliberately excluded: it is a transient migration marker.
NOTE_REQUIRED_LIFECYCLES = ["legacy", "quarantined", "deprecated", "remove"]

TAG_RES = {
    "scope": re.compile(r"^#\s*scope:\s*(.+?)\s*$"),
    "function": re.compile(r"^#\s*function:\s*(\S+)\s*$"),
    "lifecycle": re.compile(r"^#\s*lifecycle:\s*(\S+)\s*$"),
    "lifecycle-note": re.compile(r"^#\s*lifecycle-note:\s*(.+?)\s*$"),
}

BEGIN = "<!-- BEGIN generated test index -->"
END = "<!-- END generated test index -->"
BANNER = "<!-- Generated by scripts/tools/build_tests_index.py; do not edit this block by hand. -->"
# Match the block only when both markers sit at the start of their own line, so a
# literal mention of the marker inside prose is not matched.
BLOCK_RE = re.compile(
    r"(?ms)^" + re.escape(BEGIN) + r".*?^" + re.escape(END) + r"[ \t]*$"
)
# A generated block plus an optional preceding "## Test index" heading, used to
# strip orphan blocks from directories that no longer contain any test file.
STRIP_RE = re.compile(
    r"(?ms)(?:^##\s*Test index\s*\n+)?"
    + r"^"
    + re.escape(BEGIN)
    + r".*?^"
    + re.escape(END)
    + r"[ \t]*\n?"
)
HEADER_SCAN_LINES = 60


def tracked_tests() -> list[str]:
    """git-tracked ``test_*.py`` files under tests/ (pytest's python_files glob).

    conftest.py, __init__.py and helper modules do not match ``test_*.py`` and are
    therefore never indexed or required to carry tags.
    """
    out = subprocess.check_output(
        ["git", "-C", str(REPO), "ls-files", "tests/test_*.py", "tests/**/test_*.py"],
        text=True,
    )
    return sorted(out.split())


def tracked_readmes() -> list[str]:
    out = subprocess.check_output(
        ["git", "-C", str(REPO), "ls-files", "tests/README.md", "tests/**/README.md"],
        text=True,
    )
    return sorted(out.split())


def added_tests() -> set[str] | None:
    """Test files ADDED vs the upstream base (for rule 4: no new `unclassified`).

    Returns the set of ``tests/**/test_*.py`` paths added between the merge-base
    with origin/main (or origin/master / main) and HEAD, plus any newly-added
    working-tree files. Returns ``None`` when no base can be resolved, so the
    caller can skip the rule rather than fail spuriously.
    """
    base = ""
    for ref in ("origin/main", "origin/master", "main"):
        try:
            base = subprocess.check_output(
                ["git", "-C", str(REPO), "rev-parse", "--verify", ref],
                text=True,
                stderr=subprocess.DEVNULL,
            ).strip()
            break
        except subprocess.CalledProcessError:
            continue
    if not base:
        return None
    added: set[str] = set()
    for args in (
        ["diff", "--diff-filter=A", "--name-only", f"{base}...HEAD"],
        ["diff", "--diff-filter=A", "--name-only"],
        ["diff", "--cached", "--diff-filter=A", "--name-only"],
    ):
        try:
            out = subprocess.check_output(
                ["git", "-C", str(REPO), *args], text=True, stderr=subprocess.DEVNULL
            )
        except subprocess.CalledProcessError:
            continue
        for p in out.split():
            name = Path(p).name
            if (
                p.startswith("tests/")
                and name.startswith("test_")
                and p.endswith(".py")
            ):
                added.add(p)
    return added


def _first_paragraph(doc: str) -> str:
    """First blank-line-delimited paragraph of a docstring, whitespace-collapsed."""
    para: list[str] = []
    for ln in doc.splitlines():
        if ln.strip():
            para.append(ln.strip())
        elif para:
            break
    return " ".join(para)


def _tag_occurrences(text: str) -> dict[str, list[str]]:
    """All header-COMMENT matches per tag key, in order (for duplicate detection).

    A ``# scope: ...`` line that happens to sit inside a module docstring (a
    STRING token, not a COMMENT) must not satisfy the contract, so we tokenize
    rather than scan raw lines. Falls back to a raw scan on tokenizer errors.
    """
    found: dict[str, list[str]] = {k: [] for k in TAG_RES}
    try:
        for tok in tokenize.generate_tokens(io.StringIO(text).readline):
            if tok.start[0] > HEADER_SCAN_LINES:
                break
            if tok.type == tokenize.COMMENT:
                s = tok.string.strip()
                for key, rx in TAG_RES.items():
                    m = rx.match(s)
                    if m:
                        found[key].append(m.group(1))
    except (tokenize.TokenError, IndentationError, SyntaxError):
        for ln in text.splitlines()[:HEADER_SCAN_LINES]:
            for key, rx in TAG_RES.items():
                m = rx.match(ln)
                if m:
                    found[key].append(m.group(1))
    return found


def _py_tags(text: str) -> dict[str, str]:
    """First value per tag key (the value the index renders)."""
    return {k: v[0] for k, v in _tag_occurrences(text).items() if v}


def tag_multiplicity(path: str) -> dict[str, int]:
    """How many times each tag appears in the header (for exactly-once checks)."""
    text = (REPO / path).read_text(encoding="utf-8", errors="replace")
    return {k: len(v) for k, v in _tag_occurrences(text).items()}


def _split_scope(raw: str) -> tuple[str, ...]:
    return tuple(s for s in (p.strip() for p in raw.split(",")) if s)


def extract(path: str) -> tuple[tuple[str, ...], str, str, str, str]:
    """Return (scopes, function, lifecycle, note, description) for a test path."""
    text = (REPO / path).read_text(encoding="utf-8", errors="replace")
    tags = _py_tags(text)
    try:
        doc = ast.get_docstring(ast.parse(text)) or ""
    except SyntaxError:
        doc = ""
    return (
        _split_scope(tags.get("scope", "")),
        tags.get("function", ""),
        tags.get("lifecycle", ""),
        tags.get("lifecycle-note", ""),
        _first_paragraph(doc),
    )


def _cell(s: str, width: int = 100) -> str:
    s = " ".join(s.split()).replace("|", r"\|")
    return (s[: width - 1] + "…") if len(s) > width else s


def render_dir_block(rows: list[tuple[str, str, str, str, str]]) -> str:
    """rows: list of (name, scope, function, lifecycle, description)."""
    lines = [
        BEGIN,
        BANNER,
        "",
        "| Test | Scope | Function | Lifecycle | Summary |",
        "|------|-------|----------|-----------|---------|",
    ]
    for name, scope, function, lifecycle, desc in sorted(rows):
        lines.append(
            f"| `{name}` | {scope} | {function} | {lifecycle} | {_cell(desc)} |"
        )
    lines += ["", END]
    return "\n".join(lines)


def upsert_readme(dir_rel: str, block: str) -> tuple[Path, str]:
    readme = REPO / dir_rel / "README.md"
    title = dir_rel.rstrip("/")
    if readme.exists():
        content = readme.read_text(encoding="utf-8")
        m = BLOCK_RE.search(content)
        if m:
            new = content[: m.start()] + block + content[m.end() :]
        else:
            new = content.rstrip("\n") + "\n\n## Test index\n\n" + block + "\n"
    else:
        new = f"# `{title}/`\n\n{block}\n"
    return readme, new


def _matrix(
    metas: dict[str, tuple[tuple[str, ...], str, str, str, str]],
    axis: int,
    cols: list[str],
    title: str,
    note: str,
) -> list[str]:
    """scope x <axis> count matrix. A multi-scope test counts once per scope."""
    mat: dict[str, Counter] = defaultdict(Counter)
    for scopes, function, lifecycle, _note, _desc in metas.values():
        val = (function, lifecycle)[axis - 1]
        for scope in scopes or ("—",):
            mat[scope][val] += 1
    out = [f"## {title}", "", note, "", "| Scope | " + " | ".join(cols) + " | Total |"]
    out.append("|-------|" + "|".join(["------:"] * (len(cols) + 1)) + "|")
    col_tot: Counter = Counter()
    for scope in SCOPES + ["—"]:
        if scope not in mat:
            continue
        cells = [mat[scope].get(c, 0) for c in cols]
        for c, n in zip(cols, cells):
            col_tot[c] += n
        label = f"`{scope}`" if scope != "—" else "_(untagged)_"
        out.append(
            f"| {label} | " + " | ".join(str(n) for n in cells) + f" | {sum(cells)} |"
        )
    out.append(
        "| **Total** | "
        + " | ".join(str(col_tot.get(c, 0)) for c in cols)
        + f" | **{sum(col_tot.values())}** |"
    )
    return out


def render_rollup(metas: dict[str, tuple[tuple[str, ...], str, str, str, str]]) -> str:
    by_dir: dict[str, list[str]] = defaultdict(list)
    for path in metas:
        by_dir[str(Path(path).parent)].append(path)

    out = [
        BANNER.replace("this block", "this file"),
        "# tests/ inventory (generated)",
        "",
        f"Total tracked test files: **{len(metas)}**. "
        "Source of truth = each `test_*.py`'s own docstring + "
        "`# scope:` / `# function:` / `# lifecycle:` header; "
        "regenerate with `scripts/tools/build_tests_index.py`.",
        "",
    ]
    out += _matrix(
        metas,
        1,
        FUNCTIONS,
        "Scope × function",
        "Guarantee coverage per module (behavior/contract/regression/acceptance/diagnostic).",
    )
    out += [""]
    out += _matrix(
        metas,
        2,
        LIFECYCLES,
        "Scope × lifecycle",
        "Governance state per module. A multi-scope test counts once per scope.",
    )

    # Disposition queue: every non-active lifecycle, incl. unclassified.
    queue = sorted(
        (path, ",".join(sc), lc, note)
        for path, (sc, _fn, lc, note, _d) in metas.items()
        if lc in DISPOSITION_LIFECYCLES
    )
    out += ["", "## Disposition queue", ""]
    if queue:
        out.append("| Test | Scope | Lifecycle | Note / Issue |")
        out.append("|------|-------|-----------|--------------|")
        for path, sc, lc, note in queue:
            out.append(f"| `{path}` | {sc} | {lc} | {_cell(note)} |")
    else:
        out.append("_None — every test is active._")

    out += ["", "## By directory", ""]
    for d in sorted(by_dir):
        out.append(f"### `{d}/`")
        out.append("")
        out.append("| Test | Scope | Function | Lifecycle | Summary |")
        out.append("|------|-------|----------|-----------|---------|")
        for path in sorted(by_dir[d]):
            scopes, function, lifecycle, _note, desc = metas[path]
            out.append(
                f"| `{Path(path).name}` | {','.join(scopes)} | {function} | {lifecycle} | {_cell(desc)} |"
            )
        out.append("")
    return "\n".join(out).rstrip("\n") + "\n"


def build() -> tuple[
    dict[Path, str], dict[str, tuple[tuple[str, ...], str, str, str, str]]
]:
    tests = tracked_tests()
    metas: dict[str, tuple[tuple[str, ...], str, str, str, str]] = {}
    rows_by_dir: dict[str, list[tuple[str, str, str, str, str]]] = defaultdict(list)
    for path in tests:
        scopes, function, lifecycle, note, desc = extract(path)
        metas[path] = (scopes, function, lifecycle, note, desc)
        d = str(Path(path).parent)
        rows_by_dir[d].append(
            (Path(path).name, ",".join(scopes), function, lifecycle, desc)
        )
    writes: dict[Path, str] = {}
    for d, rows in rows_by_dir.items():
        block = render_dir_block(rows)
        readme, new = upsert_readme(d, block)
        writes[readme] = new
    # Orphan cleanup: a README whose directory no longer contains any test file must
    # not keep a stale generated block (e.g. after a disposition empties a dir).
    test_dirs = set(rows_by_dir)
    for rel in tracked_readmes():
        readme = REPO / rel
        if readme in writes or str(Path(rel).parent) in test_dirs:
            continue
        content = readme.read_text(encoding="utf-8")
        if STRIP_RE.search(content):
            writes[readme] = STRIP_RE.sub("", content).rstrip("\n") + "\n"
    writes[ROLLUP] = render_rollup(metas)
    return writes, metas


def main() -> int:
    check = "--check" in sys.argv
    writes, metas = build()
    stale = []
    for path, content in writes.items():
        cur = path.read_text(encoding="utf-8") if path.exists() else None
        if cur != content:
            stale.append(path)
            if not check:
                path.parent.mkdir(parents=True, exist_ok=True)
                path.write_text(content, encoding="utf-8")
    if check:
        if stale:
            print("tests index STALE (run build_tests_index.py):")
            for p in sorted(stale):
                print(f"  {p.relative_to(REPO)}")
            return 1
        print(f"tests index: ok ({len(metas)} tests, {len(writes)} files current)")
        return 0
    print(f"tests index: wrote {len(stale)} file(s) ({len(metas)} tests indexed)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
