#!/usr/bin/env python3
"""Export the bundled third-party set of the shipping package (#465 Phase C PR-C1).

Owner decision C-D1 (docs/reference/native_runtime_phase_c_scope.md §1): the
package bundles exactly the third-party objects the PR-12 formal run loaded,
byte for byte. This tool turns that run's ``deps`` manifest
(``check_shipping_tree.py deps``) into the committed pin
``shipping/third_party_set.json``: per object its SONAME, the names the run
asked for, sha256, size, the wheel it comes from, and its path inside one of
two install-time roots:

``purelib``       this venv's site-packages (torch, TensorRT, the nvidia-* wheels)
``nvjpeg_wheel``  the pinned nvidia-nvjpeg wheel ``shipping/CMakeLists.txt``
                  fetches (FetchContent ``saccade_nvjpeg_wheel``)

plus each wheel's license files (from its RECORD), which the install copies to
``licenses/``. It also writes ``shipping/THIRD_PARTY.md``, the object ->
license table installed next to them. ``developer_build_debug`` only: the
install step reads the JSON; nothing at runtime does.

Usage::

    export_third_party_set.py --deps results/465_pr12_shipping/full_c44dd876_r2/deps.json \\
        --nvjpeg-wheel build/_deps/saccade_nvjpeg_wheel-src \\
        --out shipping/third_party_set.json --notice shipping/THIRD_PARTY.md

Exit 0: written; 2: an object cannot be mapped to exactly one wheel file whose
bytes are the run's.
"""
# status: active

from __future__ import annotations

import argparse
import hashlib
import json
import re
import sys
import sysconfig
from pathlib import Path
from typing import Any

SCHEMA = "saccade.shipping_third_party/v1"
_LICENSE = re.compile(r"(^|/)(licen[cs]e|notice|eula|copying)[^/]*$", re.IGNORECASE)


class ExportError(RuntimeError):
    pass


def sha256_file(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as f:
        for chunk in iter(lambda: f.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


def wheel_records(root: Path) -> dict[str, tuple[str, list[str]]]:
    """relative file path -> (dist-info name, that wheel's license files)."""
    out: dict[str, tuple[str, list[str]]] = {}
    for record in sorted(root.glob("*.dist-info/RECORD")):
        dist = record.parent.name[: -len(".dist-info")]
        files = [
            line.split(",", 1)[0] for line in record.read_text().splitlines() if line
        ]
        licenses = sorted(f for f in files if _LICENSE.search(f))
        for f in files:
            out[f] = (dist, licenses)
    return out


def locate(source: str, roots: dict[str, Path]) -> tuple[str, str]:
    for name, root in roots.items():
        prefix = str(root.resolve()) + "/"
        if source.startswith(prefix):
            return name, source[len(prefix) :]
    raise ExportError(f"{source} is under none of the install roots {sorted(roots)}")


def export(deps: dict[str, Any], roots: dict[str, Path]) -> dict[str, Any]:
    records = {name: wheel_records(root) for name, root in roots.items()}
    entries = []
    for e in deps["entries"]:
        root, rel = locate(e["source"], roots)
        if rel not in records[root]:
            raise ExportError(f"{rel} is in no wheel RECORD under {root}")
        dist, licenses = records[root][rel]
        got = sha256_file(roots[root] / rel)
        if got != e["sha256"]:
            raise ExportError(
                f"{root}/{rel}: sha256 {got} is not the run's {e['sha256']}"
            )
        license_files = [
            {"path": lic, "sha256": sha256_file(roots[root] / lic)} for lic in licenses
        ]
        if not license_files:
            raise ExportError(f"wheel {dist} ({rel}) has no license file in its RECORD")
        entries.append(
            {
                "soname": e["soname"],
                "names": e["names"],
                "sha256": e["sha256"],
                "bytes": e["bytes"],
                "source": {"root": root, "path": rel},
                "wheel": dist,
                "license_files": license_files,
            }
        )
    entries.sort(key=lambda x: x["soname"])
    return {
        "schema": SCHEMA,
        "reading": (
            "The third-party shared objects the shipping package bundles at lib/vendor/ "
            "(owner decision C-D1): exactly the set the PR-12 formal run loaded, by sha256. "
            "The install copies each from its root and refuses any other bytes. Generated by "
            "scripts/native/export_third_party_set.py; do not edit by hand."
        ),
        "origin": deps.get("loaded", ""),
        "roots": {
            "purelib": "this venv's site-packages",
            "nvjpeg_wheel": "FetchContent saccade_nvjpeg_wheel (shipping/CMakeLists.txt)",
        },
        "entries": entries,
    }


def notice(set_: dict[str, Any]) -> str:
    by_wheel: dict[str, list[dict[str, Any]]] = {}
    for e in set_["entries"]:
        by_wheel.setdefault(e["wheel"], []).append(e)
    lines = [
        "# Third-party components",
        "",
        "Generated by `scripts/native/export_third_party_set.py` from "
        "`shipping/third_party_set.json`; do not edit by hand.",
        "",
        "The shared objects under `lib/vendor/` are third-party components distributed "
        "under their own license terms, copied unmodified from the wheels named below. "
        "They are not covered by Saccade's Apache-2.0 license. Each wheel's license "
        "files are under `licenses/<wheel>/`.",
        "",
        "| wheel | objects | license files |",
        "|:--|:--|:--|",
    ]
    for wheel in sorted(by_wheel):
        objs = ", ".join(f"`{e['soname']}`" for e in by_wheel[wheel])
        lics = ", ".join(
            f"`{f['path'].rsplit('/', 1)[-1]}`"
            for f in by_wheel[wheel][0]["license_files"]
        )
        lines.append(f"| `{wheel}` | {objs} | {lics} |")
    return "\n".join(lines) + "\n"


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--deps", type=Path, required=True)
    ap.add_argument("--nvjpeg-wheel", type=Path, required=True)
    ap.add_argument(
        "--purelib", type=Path, default=Path(sysconfig.get_paths()["purelib"])
    )
    ap.add_argument("--out", type=Path, required=True)
    ap.add_argument("--notice", type=Path, required=True)
    args = ap.parse_args(argv)
    try:
        set_ = export(
            json.loads(args.deps.read_text()),
            {"purelib": args.purelib, "nvjpeg_wheel": args.nvjpeg_wheel},
        )
    except ExportError as exc:
        print(f"export_third_party_set: {exc}", file=sys.stderr)
        return 2
    args.out.write_text(json.dumps(set_, indent=2) + "\n")
    args.notice.write_text(notice(set_))
    print(f"{len(set_['entries'])} objects -> {args.out}, {args.notice}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
