#!/usr/bin/env python3
# status: diagnostic
"""The licence audit of the bundled third-party set (#465 Phase C PR-C4).

``shipping/license_audit.json`` records, per object in
``shipping/third_party_set.json``: the licence text its wheel carries (the
files the package ships under ``licenses/<wheel>/``), the version-matched
official terms (URL, fetch time, sha256 of the snapshot), whether each grants
distribution of that object (an Attachment A name, a quoted clause, or a file
identical to the shipped one), the conditions, a status and the open risks.
It is a reading of licence texts, not a legal conclusion
(docs/reference/native_runtime_resolved_config.md §20). Every claim is checked
against the object's own wheel's files: two wheels whose files have the same
bytes are still checked one by one.

Subcommands:

``render``  write ``shipping/THIRD_PARTY.md`` from the third-party set and the
            audit (``--out``), or with ``--check`` exit 1 if the committed file
            is not that rendering.
``check``   ``coverage``: the audit names exactly the set's objects, each with
            its wheel, a known status, known sources and conditions;
            ``bundled_texts`` (``--licenses DIR``: a tree's ``licenses/``, or
            ``--purelib`` + ``--nvjpeg-wheel``): each shipped licence file has
            the set's sha256, and each object's claims about it hold (Attachment
            A lists / does not list its name, a clause or condition appears
            verbatim up to whitespace, a token is absent); ``official_terms``
            (``--sources DIR``, the snapshots): each snapshot has the recorded
            sha256, each object's claims about the official terms hold, and the
            release the audit names matches the wheel's version (the
            documentation's version switcher, the release notes' component
            table, or the tag in the URL); ``notice``: the committed
            THIRD_PARTY.md is the rendering. A check that was not given its
            inputs is reported as ``skipped``, not passed.

Usage::

    license_audit.py render --out shipping/THIRD_PARTY.md
    license_audit.py check --licenses TREE/licenses --sources SNAPSHOTS --report audit.json

Exit 0: every check that ran passes; 1: a check fails; 2: error.
"""

from __future__ import annotations

import argparse
import hashlib
import html
import json
import re
import sys
from pathlib import Path
from typing import Any

SCHEMA = "saccade.shipping_license_audit_check/v1"
AUDIT_SCHEMA = "saccade.shipping_license_audit/v1"
REPO = Path(__file__).resolve().parents[2]
THIRD_PARTY_SET = REPO / "shipping/third_party_set.json"
AUDIT = REPO / "shipping/license_audit.json"
NOTICE = REPO / "shipping/THIRD_PARTY.md"


def _load(path: Path) -> dict[str, Any]:
    return json.loads(path.read_text())


def _sha256(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def normalize(text: str) -> str:
    return re.sub(r"\s+", " ", text).strip()


def page_text(data: bytes) -> str:
    """The visible text of a snapshot (HTML or plain), whitespace-normalized."""
    t = data.decode("utf-8", errors="replace")
    if "<html" in t[:4096].lower() or "<!doctype html" in t[:4096].lower():
        t = re.sub(r"<script.*?</script>|<style.*?</style>", " ", t, flags=re.S)
        t = html.unescape(re.sub(r"<[^>]+>", " ", t))
    return normalize(t)


def attachment_a(text: str) -> str | None:
    """The CUDA EULA's Attachment A section (from its heading to Attachment B),
    or None when the text has none. The heading also appears in the table of
    contents of an HTML page, so the longest such span is the section."""
    spans = []
    for m in re.finditer(r"2\.6\.? Attachment A", text):
        end = text.find("Attachment B", m.end())
        spans.append(text[m.start() : end if end > 0 else len(text)])
    return max(spans, key=len) if spans else None


def version_of(wheel: str) -> str:
    return wheel.rsplit("-", 1)[1]


# ---------------------------------------------------------------- render


def render(set_: dict[str, Any], audit: dict[str, Any]) -> str:
    entries = {e["soname"]: e for e in set_["entries"]}
    sources = audit["sources"]
    lines = [
        "# Third-party components",
        "",
        "Generated by `scripts/native/license_audit.py render` from "
        "`shipping/third_party_set.json` and `shipping/license_audit.json`; do not edit by hand.",
        "",
        "The shared objects under `lib/vendor/` are third-party components distributed "
        "under their own license terms, copied unmodified from the wheels named below. "
        "They are not covered by Saccade's Apache-2.0 license. Each wheel's license "
        "files are under `licenses/<wheel>/`.",
        "",
        "What follows is a reading of the license texts, not a legal conclusion.",
        "",
        f"**Distribution status: {audit['distribution']['status']}.** "
        + audit["distribution"]["reading"],
        "",
        "## Objects",
        "",
        "| object | wheel | license files | shipped text grants distribution | version-matched official terms | status |",
        "|:--|:--|:--|:--|:--|:--|",
    ]
    for o in audit["objects"]:
        e = entries[o["soname"]]
        lics = ", ".join(
            f"`{f['path'].rsplit('/', 1)[-1]}`" for f in e["license_files"]
        )
        b = o["bundled"]
        if "attachment_a" in b:
            a = b["attachment_a"]
            shipped = f"Attachment A {'lists' if a['listed'] else 'does not list'} `{a['name']}`"
        elif "clause" in b:
            shipped = "yes (quoted in the audit)"
        else:
            shipped = "no text for this object"
        official = "; ".join(_official_summary(c, sources) for c in o["official"])
        lines.append(
            f"| `{o['soname']}` | `{o['wheel']}` | {lics} | {shipped} | {official} | `{o['status']}` |"
        )
    lines += ["", "Statuses:", ""]
    for k, v in audit["statuses"].items():
        lines.append(f"- `{k}`: {v}")
    lines += ["", "## Open items", ""]
    for o in audit["objects"]:
        for r in o["risks"]:
            lines.append(f"- `{o['soname']}`: {r}")
    lines += ["", "## Distribution conditions (quoted)", ""]
    for k, conds in audit["conditions"].items():
        users = sorted({o["wheel"] for o in audit["objects"] if o["conditions"] == k})
        lines.append(f"- {', '.join(f'`{u}`' for u in users)}:")
        for c in conds:
            lines.append(f"  - “{c}”")
    lines += ["", "## Sources", ""]
    for k, s in sources.items():
        lines.append(
            f"- `{k}`: {s['version']}. <{s['url']}> (fetched {s['fetched']}, sha256 `{s['sha256'][:16]}…`)"
        )
    return "\n".join(lines) + "\n"


def _official_summary(claim: dict[str, Any], sources: dict[str, Any]) -> str:
    src = f"`{claim['source']}`"
    if "attachment_a" in claim:
        a = claim["attachment_a"]
        return f"{src}: Attachment A {'lists' if a['listed'] else 'does not list'} `{a['name']}`"
    if "identical_to_bundled" in claim:
        return f"{src}: identical to the shipped `{claim['identical_to_bundled']}`"
    if "prefix_of_bundled" in claim:
        return f"{src}: the start of the shipped `{claim['prefix_of_bundled']}`"
    return f"{src}: grants (quoted in the audit)"


# ---------------------------------------------------------------- check


# Statuses that assert a grant in the shipped text / in the official terms.
SHIPPED_GRANT_STATUSES = ("grant_in_bundled_and_official", "grant_in_both_texts_differ")
OFFICIAL_GRANT_STATUSES = (*SHIPPED_GRANT_STATUSES, "grant_in_official_only")
# The row label of each CUDA component wheel in the release notes' "Component
# Versions" table; a release-notes release is matched on that row only.
RELNOTES_COMPONENT = {
    "nvidia_cuda_runtime": "CUDA Runtime (cudart)",
    "nvidia_cublas": "CUDA cuBLAS",
    "nvidia_cufft": "CUDA cuFFT",
    "nvidia_cufile": "CUDA cuFile",
    "nvidia_curand": "CUDA cuRAND",
    "nvidia_cusparse": "CUDA cuSPARSE",
    "nvidia_nvjitlink": "CUDA nvJitLink",
    "nvidia_nvjpeg": "CUDA nvJPEG",
    "nvidia_cuda_nvrtc": "CUDA NVRTC",
    "nvidia_cuda_cupti": "CUPTI",
}


def grants(claim: dict[str, Any]) -> bool:
    """Whether an official claim asserts that the terms grant distribution:
    a listed Attachment A name, a quoted clause, or upstream text identical to
    (or the start of) the shipped grant text. A not-listed name does not."""
    if "attachment_a" in claim:
        return claim["attachment_a"]["listed"] is True
    return any(
        k in claim for k in ("clause", "identical_to_bundled", "prefix_of_bundled")
    )


def component_versions(text: str, label: str) -> list[str]:
    """The versions in `label`'s row of the release notes' component table."""
    start = text.find("Component Versions")
    if start < 0:
        return []
    end = text.find("Table 2", start)
    table = text[start : end if end > 0 else len(text)]
    return re.findall(rf"(?<![\w(]){re.escape(label)} (\d[\d.]*)", table)


def check_coverage(set_: dict[str, Any], audit: dict[str, Any]) -> list[str]:
    bad = []
    if audit.get("schema") != AUDIT_SCHEMA:
        bad.append(f"schema {audit.get('schema')!r} != {AUDIT_SCHEMA}")
    want = {e["soname"]: e["wheel"] for e in set_["entries"]}
    got: dict[str, str] = {}
    for o in audit["objects"]:
        if o["soname"] in got:
            bad.append(f"{o['soname']}: listed twice")
        got[o["soname"]] = o["wheel"]
        if o["status"] not in audit["statuses"]:
            bad.append(f"{o['soname']}: unknown status {o['status']!r}")
        if o["conditions"] is None and o["status"] != "no_licence_text_shipped":
            bad.append(f"{o['soname']}: no conditions but status {o['status']}")
        if o["conditions"] is not None and o["conditions"] not in audit["conditions"]:
            bad.append(f"{o['soname']}: unknown conditions {o['conditions']!r}")
        if o["status"] != "grant_in_bundled_and_official" and not o["risks"]:
            bad.append(f"{o['soname']}: status {o['status']} without a risk")
        for c in [o["release"], *o["official"]]:
            if c["source"] not in audit["sources"]:
                bad.append(f"{o['soname']}: unknown source {c['source']!r}")
        b = o["bundled"]
        kinds = [k for k in ("attachment_a", "clause", "absent") if k in b]
        if len(kinds) != 1:
            bad.append(
                f"{o['soname']}: bundled claim must be one of attachment_a/clause/absent, has {kinds}"
            )
        if "absent" in b and o["status"] != "no_licence_text_shipped":
            bad.append(f"{o['soname']}: no shipped text but status {o['status']}")
        if (
            b.get("attachment_a", {}).get("listed") is False
            and o["status"] != "grant_in_official_only"
        ):
            bad.append(f"{o['soname']}: shipped text silent but status {o['status']}")
        shipped_grants = (
            b.get("attachment_a", {}).get("listed") is True or "clause" in b
        )
        if shipped_grants and o["status"] not in SHIPPED_GRANT_STATUSES:
            bad.append(f"{o['soname']}: shipped text grants but status {o['status']}")
        if o["status"] in OFFICIAL_GRANT_STATUSES and not any(
            grants(c) for c in o["official"]
        ):
            bad.append(
                f"{o['soname']}: status {o['status']} without an official claim that grants distribution"
            )
    for s in sorted(set(want) | set(got)):
        if s not in got:
            bad.append(f"{s}: in the third-party set but not in the audit")
        elif s not in want:
            bad.append(f"{s}: in the audit but not in the third-party set")
        elif want[s] != got[s]:
            bad.append(f"{s}: wheel {got[s]} != the set's {want[s]}")
    return bad


def _claim_problems(
    who: str, claim: dict[str, Any], text: str, conds: list[str] | None = None
) -> list[str]:
    bad = []
    if "attachment_a" in claim:
        a = claim["attachment_a"]
        section = attachment_a(text)
        if section is None:
            bad.append(f"{who}: no Attachment A section")
        elif (a["name"] in section) != a["listed"]:
            bad.append(
                f"{who}: Attachment A {'does not list' if a['listed'] else 'lists'} {a['name']!r}"
            )
    if "clause" in claim and normalize(claim["clause"]) not in text:
        bad.append(f"{who}: clause not found: {claim['clause'][:80]!r}")
    if "absent" in claim and claim["absent"].lower() in text.lower():
        bad.append(f"{who}: {claim['absent']!r} is present")
    for c in conds or []:
        if normalize(c) not in text:
            bad.append(f"{who}: condition not found: {c[:80]!r}")
    return bad


def shipped_files(
    set_: dict[str, Any],
    licenses: Path | None,
    roots: dict[str, Path] | None,
) -> tuple[dict[str, list[bytes]], list[str]]:
    """wheel -> its shipped licence files' bytes, each checked against the set."""
    out: dict[str, list[bytes]] = {}
    bad = []
    for e in set_["entries"]:
        if e["wheel"] in out:
            continue
        files = []
        for lic in e["license_files"]:
            if licenses is not None:
                p = licenses / e["wheel"] / lic["path"].rsplit("/", 1)[-1]
            else:
                assert roots is not None
                p = roots[e["source"]["root"]] / lic["path"]
            data = p.read_bytes() if p.is_file() else b""
            if _sha256(data) != lic["sha256"]:
                bad.append(f"{p}: not the set's {lic['sha256']}")
            files.append(data)
        out[e["wheel"]] = files
    return out, bad


def check_bundled(audit: dict[str, Any], shipped: dict[str, list[bytes]]) -> list[str]:
    bad = []
    for o in audit["objects"]:
        # This object's own wheel's files, read and searched for this object.
        text = page_text(b"\n".join(shipped[o["wheel"]]))
        conds = audit["conditions"].get(o["conditions"]) if o["conditions"] else None
        bad += _claim_problems(f"{o['soname']} (shipped)", o["bundled"], text, conds)
    return bad


def _switcher(data: bytes) -> str | None:
    m = re.search(rb"theme_switcher_version_match = '([^']*)'", data)
    return m.group(1).decode() if m else None


def _archive(url: str) -> str | None:
    m = re.search(r"/archive/(\d[\d.]*)/", url)
    return m.group(1) if m else None


def source_bound(
    o: dict[str, Any],
    source: str,
    audit: dict[str, Any],
    snap: dict[str, bytes],
    release: bool,
) -> tuple[bool | None, str]:
    """Whether `source` is the terms (or release record) of this object's
    version: True, False (a mismatch), or None (unversioned: accepted only as
    the object's own release source, with a risk recorded; reported).

    * a documentation version switcher: the wheel version starts with it;
    * the release notes (the object's release): the wheel version is in the
      object's own component row (RELNOTES_COMPONENT), not anywhere on the page;
    * an archive URL ``/archive/<x>/``: the object's release source is an
      archive page of the same <x> that matches by the rules above;
    * a tag in the URL ``/v<version>[-n]/``: the wheel version."""
    ver = version_of(o["wheel"])
    url = audit["sources"][source]["url"]
    data = snap[source]
    who = f"{o['soname']}: {'release' if release else 'terms'} {source}"
    sw = _switcher(data)
    if sw is not None:
        ok = ver.startswith(sw.lstrip("v"))
        return ok, f"{who} is version {sw}, the wheel is {ver}"
    if release and ("release-notes" in url or "relnotes" in source):
        label = RELNOTES_COMPONENT.get(o["wheel"].rsplit("-", 1)[0])
        if label is None:
            return False, f"{who}: no component row known for {o['wheel']}"
        rows = component_versions(page_text(data), label)
        return rows == [ver], f"{who}: row {label!r} gives {rows}, the wheel is {ver}"
    arch = _archive(url)
    if arch is not None and not release:
        rel_src = o["release"]["source"]
        rel_ok, _ = source_bound(o, rel_src, audit, snap, release=True)
        same = _archive(audit["sources"][rel_src]["url"]) == arch
        return (
            bool(rel_ok) and same,
            f"{who} is archive {arch}; the release {rel_src} is "
            f"{_archive(audit['sources'][rel_src]['url'])} (matched: {rel_ok})",
        )
    if re.search(rf"/v{re.escape(ver)}(-\d+)?/", url):
        return True, f"{who} tag v{ver}"
    if source == o["release"]["source"] and o["risks"]:
        return None, f"{who} not matched to {ver} (unversioned; risk recorded)"
    return False, f"{who} is not tied to version {ver}"


def check_official(
    audit: dict[str, Any], sources_dir: Path, shipped: dict[str, list[bytes]] | None
) -> tuple[list[str], list[str]]:
    """(problems, notes); notes name the release matches that cannot be checked."""
    bad: list[str] = []
    notes: list[str] = []
    snap: dict[str, bytes] = {}
    for k, s in audit["sources"].items():
        p = sources_dir / s["snapshot"]
        data = p.read_bytes() if p.is_file() else b""
        if _sha256(data) != s["sha256"]:
            bad.append(f"source {k}: {p} is not sha256 {s['sha256']}")
        snap[k] = data
    for o in audit["objects"]:
        for c in o["official"]:
            data = snap[c["source"]]
            who = f"{o['soname']} ({c['source']})"
            bad += _claim_problems(who, c, page_text(data))
            for key, same in (
                ("identical_to_bundled", True),
                ("prefix_of_bundled", False),
            ):
                if key not in c:
                    continue
                if shipped is None:
                    bad.append(f"{who}: {key} needs the shipped files")
                    continue
                e_files = shipped[o["wheel"]]
                names = [f for f in e_files if f]
                match = any((f == data) if same else f.startswith(data) for f in names)
                if not match:
                    bad.append(f"{who}: {key} {c[key]} does not hold")
        rel_ok, rel_why = source_bound(
            o, o["release"]["source"], audit, snap, release=True
        )
        if rel_ok is False:
            bad.append(rel_why)
        elif rel_ok is None:
            notes.append(rel_why)
        for c in o["official"]:
            if not grants(c) or c["source"] == o["release"]["source"]:
                continue
            ok, why = source_bound(o, c["source"], audit, snap, release=False)
            if ok is False:
                bad.append(why)
            elif ok is None:
                notes.append(why)
    return bad, notes


def cmd_render(args: argparse.Namespace) -> int:
    text = render(_load(args.third_party_set), _load(args.audit))
    if args.check:
        same = args.out.is_file() and args.out.read_text() == text
        print(f"{args.out}: {'is' if same else 'is NOT'} the rendering")
        return 0 if same else 1
    args.out.write_text(text)
    print(f"wrote {args.out}")
    return 0


def cmd_check(args: argparse.Namespace) -> int:
    set_ = _load(args.third_party_set)
    audit = _load(args.audit)
    checks: dict[str, Any] = {}
    checks["coverage"] = {"problems": check_coverage(set_, audit)}

    shipped = None
    if args.licenses or args.purelib:
        roots = None
        if args.licenses is None:
            roots = {"purelib": args.purelib, "nvjpeg_wheel": args.nvjpeg_wheel}
        shipped, files_bad = shipped_files(set_, args.licenses, roots)
        checks["bundled_texts"] = {
            "problems": files_bad + check_bundled(audit, shipped)
        }
    else:
        checks["bundled_texts"] = {"skipped": "no --licenses / --purelib"}

    if args.sources:
        bad, notes = check_official(audit, args.sources, shipped)
        checks["official_terms"] = {"problems": bad, "unmatched_releases": notes}
    else:
        checks["official_terms"] = {"skipped": "no --sources"}

    notice_ok = args.notice.is_file() and args.notice.read_text() == render(set_, audit)
    checks["notice"] = {
        "problems": [] if notice_ok else [f"{args.notice} is not the rendering"]
    }
    for c in checks.values():
        if "skipped" not in c:
            c["pass"] = not c["problems"]
    report = {
        "schema": SCHEMA,
        "audit": str(args.audit),
        "audit_sha256": _sha256(args.audit.read_bytes()),
        "distribution": audit["distribution"]["status"],
        "statuses": {
            s: sorted(o["soname"] for o in audit["objects"] if o["status"] == s)
            for s in audit["statuses"]
        },
        "checks": checks,
        "pass": all(c.get("pass", True) for c in checks.values()),
        "complete": not any("skipped" in c for c in checks.values()),
    }
    if args.report:
        args.report.write_text(json.dumps(report, indent=2) + "\n")
    for k, c in checks.items():
        state = "SKIPPED" if "skipped" in c else ("PASS" if c["pass"] else "FAIL")
        print(f"{k}: {state}")
        for p in c.get("problems", [])[:20]:
            print(f"  {p}")
    return 0 if report["pass"] else 1


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--third-party-set", type=Path, default=THIRD_PARTY_SET)
    ap.add_argument("--audit", type=Path, default=AUDIT)
    sub = ap.add_subparsers(dest="cmd", required=True)
    r = sub.add_parser("render")
    r.add_argument("--out", type=Path, default=NOTICE)
    r.add_argument("--check", action="store_true")
    c = sub.add_parser("check")
    c.add_argument("--licenses", type=Path, help="a tree's licenses/ directory")
    c.add_argument(
        "--purelib", type=Path, help="the wheels' site-packages (instead of --licenses)"
    )
    c.add_argument(
        "--nvjpeg-wheel",
        type=Path,
        default=REPO / "build/_deps/saccade_nvjpeg_wheel-src",
    )
    c.add_argument("--sources", type=Path, help="the official-terms snapshots")
    c.add_argument("--notice", type=Path, default=NOTICE)
    c.add_argument("--report", type=Path)
    args = ap.parse_args(argv)
    try:
        return cmd_render(args) if args.cmd == "render" else cmd_check(args)
    except (OSError, KeyError, ValueError) as exc:
        print(f"license_audit: {exc}", file=sys.stderr)
        return 2


if __name__ == "__main__":
    sys.exit(main())
